name: "Install yq tool"
description: "Install yq tool by our script"

inputs:
  architecture:
    description: "Architecture"
    required: false
    default: "amd64"

runs:
  using: "composite"
  steps:
    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1
      with:
        version: '${{ inputs.version }}'
        download-compressed: '${{ inputs.download-compressed }}'
        force: '${{ inputs.force }}'
